SeaBattle/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('battle/', include('battle.urls')),
]

battle/urls.py
from django.urls import path
from . import views

app_name = 'battle'
urlpatterns = [
    path('', views.index, name='index'),

    path('create_game/', views.create_game, name='create_game'),
    path('join_game/<str:room_name>', views.join_game, name='join_game'),


    path('back_player1/', views.back_player1, name='back_player1'),
    path('back_player2/', views.back_player2, name='back_player2'),

    path('game_user1/', views.game_user1, name='game_user1'),
    path('game_user2/', views.game_user2, name='game_user2'),

    path('interact_battlefield1/', views.interact_battlefield1, name='interact_battlefield1'),
    path('interact_battlefield2/', views.interact_battlefield2, name='interact_battlefield2'),

    path('win/', views.player_win, name='player_win'),
    path('lose/', views.player_lose, name='player_lose'),

    path('game_not_found/', views.game_not_found, name='game_not_found'),
    path('surrender/', views.surrender, name='surrender'),

    path('check_user_game/', views.check_user_game, name='check_user_game')

]

users/urls.py
from django.urls import path
from .views import login, register, login_user, logout_user

app_name = 'users'

urlpatterns = [
    path('', login, name='login'),
    path('registration/', register, name='register'),
    path('logout/', logout_user, name='logout_user'),
]

battle/models.py
from django.db import models
from django.contrib.auth.models import User


class Gamer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    games = models.IntegerField(default=0, verbose_name='games')
    wins = models.IntegerField(default=0, verbose_name='wins')
    in_lobby = models.BooleanField(default=False, verbose_name='in_lobby')
    in_game = models.BooleanField(default=False, verbose_name='in_game')
    profile_image = models.ImageField(verbose_name='Profile_image')


class Game(models.Model):
    room_name = models.CharField(null=True, max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    player1 = models.ForeignKey(Gamer, on_delete=models.CASCADE, related_name='gamer')
    player2 = models.ForeignKey(Gamer, on_delete=models.CASCADE, null=True)
    player1_move = models.BooleanField(default=1)
    player2_move = models.BooleanField(default=0)
    battlefield_player1 = models.TextField(max_length=1000, null=True)
    battlefield_player2 = models.TextField(max_length=1000, null=True)

    def __str__(self):
        return self.player1

SeaBattle/battle/views.py
from django.shortcuts import render
from .game_logic.logic import back1, back2, start_battle_user, prepare_game, get_gamer, delete_game
from .game_logic.decorators import not_in_game, lose_redirect_player1
import battle
from .models import Gamer, Game
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse


@login_required
@not_in_game
def index(request):
    """Create main menu and delete button 'Create game' if user have a game"""
    gamer = Gamer.objects.get(user_id=request.user.id)
    games = Game.objects.filter(player2=None).order_by('user_id')
    user_games = len(Game.objects.all().filter(player1=gamer))
    if request.method == 'GET':
        return render(request, 'battle/index.html', {'games': games, 'user_games': user_games, 'gamer': gamer})


@login_required
def create_game(request):
    """Create user game if he haven't game room"""
    if request.method == 'GET':
        user = request.user
        gamer = prepare_game(request)
        try:
            Game.objects.get(player1=gamer)
        except battle.models.Game.DoesNotExist:
            game = Game()
            game.player1 = gamer
            game.room_name = user.username
            game.save()
        return render(request, "battle/create_game.html")


@not_in_game
def join_game(request, room_name):
    """Add user to model player2"""
    if request.method == 'GET':
        gamer = prepare_game(request)
        game = Game.objects.get(room_name=room_name)
        game.player2 = gamer
        game.save()
        return render(request, "battle/join_game.html")


def game_user1(request):
    """Get user1 battlefield from ajax as str and add it to model battlefield 1 field"""
    gamer = start_battle_user(request)
    game = Game.objects.get(player1=gamer)
    if request.method == 'POST':
        battlefield = request.POST.get('battlefield')
        game.battlefield_player1 = battlefield
        game.save()
    return render(request, 'battle/game_user1.html', {'game': game})


def game_user2(request):
    """Get user2 battlefield from ajax as str and add it to model battlefield 2 field"""
    gamer = start_battle_user(request)
    game = Game.objects.get(player2=gamer)
    if request.method == 'POST':
        battlefield = request.POST.get('battlefield')
        game.battlefield_player2 = battlefield
        game.save()
    return render(request, 'battle/game_user2.html', {'game': game})


def interact_battlefield1(request):
    """
    Get game object and return battlefield_player1 to JS
    """
    gamer = get_gamer(request)
    try:
        game = Game.objects.get(player1=gamer)
    except battle.models.Game.DoesNotExist:
        game = Game.objects.get(player2=gamer)

    if request.method == "GET":
        battlefield1 = game.battlefield_player1
        return HttpResponse(battlefield1)
    else:
        battlefield = request.POST.get('battlefield')
        game.battlefield_player1 = battlefield
        game.save()
        return HttpResponse("Success")


def interact_battlefield2(request):
    """
    Get game object and return battlefield_player2 to JS
    """
    gamer = get_gamer(request)
    try:
        game = Game.objects.get(player2=gamer)
    except battle.models.Game.DoesNotExist:
        game = Game.objects.get(player1=gamer)

    if request.method == "GET":
        battlefield2 = game.battlefield_player2
        return HttpResponse(battlefield2)
    else:
        battlefield = request.POST.get('battlefield')
        game.battlefield_player2 = battlefield
        game.save()
        return HttpResponse("Success")


def player_win(request):
    """add win to user and redirect to win page"""
    gamer = get_gamer(request)
    gamer.games += 1
    gamer.wins += 1
    gamer.save()
    return render(request, 'battle/win_page.html', {'gamer': gamer})


def player_lose(request):
    """delete game and redirect to lose page"""
    gamer = get_gamer(request)
    delete_game(request, gamer)
    gamer.games += 1
    gamer.save()
    return render(request, 'battle/lose_page.html', {'gamer': gamer})


def back_player1(request):
    return back1(request)


def back_player2(request):
    return back2(request)

battle/views.py
from django.shortcuts import render, redirect
from .game_logic.logic import back1, back2, start_battle_user, prepare_game, get_gamer, delete_game, \
    check_win_or_lose
from .game_logic.decorators import not_in_game, game_not_found_redirect
import battle
from .models import Gamer, Game
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse


@login_required
@not_in_game
def index(request):
    """Create main menu and delete button 'Create game' if user have a game"""
    gamer = Gamer.objects.get(user_id=request.user.id)
    games = Game.objects.filter(player2=None).order_by('user_id')
    user_games = len(Game.objects.all().filter(player1=gamer))
    if request.method == 'GET':
        return render(request, 'battle/index.html', {'games': games, 'user_games': user_games, 'gamer': gamer})


@login_required
def create_game(request):
    """Create user game if he haven't game room"""
    if request.method == 'GET':
        user = request.user
        gamer = prepare_game(request)
        try:
            game = Game.objects.get(player1=gamer)
            if game.battlefield_player1 is not None:
                return redirect('battle:game_user1')
        except battle.models.Game.DoesNotExist:
            game = Game()
            game.player1 = gamer
            game.room_name = user.username
            game.save()
        return render(request, "battle/create_game.html")


def join_game(request, room_name):
    """Add user to model player2"""
    gamer = prepare_game(request)
    if request.method == 'GET':
        try:
            game = Game.objects.get(room_name=room_name)
            if game.battlefield_player2 is not None:
                return redirect('battle:index')
        except battle.models.Game.DoesNotExist:
            redirect('battle:game_not_found')
        game.player2 = gamer
        game.save()
        return render(request, "battle/join_game.html")


@login_required
@game_not_found_redirect
def game_user1(request):
    """Get user1 battlefield from ajax as str and add it to model battlefield 1 field"""
    gamer = start_battle_user(request)
    game = Game.objects.get(player1=gamer)
    if request.method == 'POST':
        battlefield = request.POST.get('battlefield')
        if game.battlefield_player1 is None:
            game.battlefield_player1 = battlefield
        game.save()
    if game.battlefield_player1 is None:
        return redirect('battle:create_game')
    return render(request, 'battle/game_user1.html', {'game': game})


@login_required
@game_not_found_redirect
def game_user2(request):
    """Get user2 battlefield from ajax as str and add it to model battlefield 2 field"""
    gamer = start_battle_user(request)
    game = Game.objects.get(player2=gamer)
    if request.method == 'POST':
        battlefield = request.POST.get('battlefield')
        if game.battlefield_player2 is None:
            game.battlefield_player2 = battlefield
        game.save()
    if game.battlefield_player2 is None:
        return redirect('battle:join_game', game.room_name)
    return render(request, 'battle/game_user2.html', {'game': game})


def interact_battlefield1(request):
    """
    Get game object and return battlefield_player1 to JS
    """
    gamer = get_gamer(request)
    try:
        game = Game.objects.get(player1=gamer)
    except battle.models.Game.DoesNotExist:
        try:
            game = Game.objects.get(player2=gamer)
        except battle.models.Game.DoesNotExist:
            return redirect('battle:game_not_found')

    if request.method == "GET":
        battlefield1 = game.battlefield_player1
        return HttpResponse(battlefield1)
    else:
        battlefield = request.POST.get('battlefield')
        game.battlefield_player1 = battlefield
        game.save()
        return HttpResponse("Success")


def interact_battlefield2(request):
    """
    Get game object and return battlefield_player2 to JS
    """
    gamer = get_gamer(request)
    try:
        game = Game.objects.get(player2=gamer)
    except battle.models.Game.DoesNotExist:
        try:
            game = Game.objects.get(player1=gamer)
        except battle.models.Game.DoesNotExist:
            return redirect('battle:game_not_found')
    if request.method == "GET":
        battlefield2 = game.battlefield_player2
        return HttpResponse(battlefield2)
    else:
        battlefield = request.POST.get('battlefield')
        game.battlefield_player2 = battlefield
        game.save()
        return HttpResponse("Success")


@game_not_found_redirect
def player_win(request):
    """add win to user and redirect to win page"""
    gamer = get_gamer(request)
    player_redirect = check_win_or_lose(request, gamer)
    if player_redirect == 1:
        return redirect('battle:game_user1')
    if player_redirect == 2:
        return redirect('battle:game_user2')
    gamer.games += 1
    gamer.wins += 1
    gamer.save()
    return render(request, 'battle/win_page.html', {'gamer': gamer})


@game_not_found_redirect
def player_lose(request):
    """delete game and redirect to lose page"""
    gamer = get_gamer(request)
    player_redirect = check_win_or_lose(request, gamer)
    if player_redirect == 1:
        return redirect('battle:game_user1')
    if player_redirect == 2:
        return redirect('battle:game_user2')
    delete_game(request, gamer)
    gamer.games += 1
    gamer.save()
    return render(request, 'battle/lose_page.html', {'gamer': gamer})



def back_player1(request):
    return back1(request)


def back_player2(request):
    return back2(request)


def game_not_found(request):
    """Page if one of the players gave up"""
    return render(request, 'battle/game_not_found.html')


@game_not_found_redirect
def surrender(request):
    """Delete the game"""
    gamer = get_gamer(request)
    # Get user and his role
    try:
        game = Game.objects.get(player1=gamer)
        player1 = True
    except battle.models.Game.DoesNotExist:
        game = Game.objects.get(player2=gamer)
        player1 = False

    # Add one game if first user surrender when second user join to game
    if player1:
        if game.player2 is not None:
            gamer.games += 1
            game.player2.wins += 1
    else:
        gamer.games += 1
        game.player1.wins += 1
    game.delete()
    gamer.save()
    return redirect('battle:index')


def check_user_game(request):
    """Check game for reset localstorage in index page JS"""
    gamer = get_gamer(request)
    try:
        game = Game.objects.get(player1=gamer)
        return HttpResponse("true")
    except battle.models.Game.DoesNotExist:
        try:
            game = Game.objects.get(player2=gamer)
            return HttpResponse("true")
        except battle.models.Game.DoesNotExist:
            return HttpResponse('false')

battle/templates/battle/create_game.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Preparing for battle</title>
  <link rel="stylesheet" href="{% static 'css/create_game.css' %}">
</head>
<body>
  <H2>Arrange your ships</H2>
  <div id="battlefield">
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>

  </div>
  <div class="ships">
    <div id="ship4"></div>
    <div id="ship3"></div>
    <div id="ship21"></div>
    <div id="ship22"></div>
    <div id="ship11"></div>
    <div id="ship12"></div>
    <div id="ship13"></div>
  </div>
  <div class="navigation">
    <a class="back" href="{% url 'battle:back_player1' %}">Back</a>
    <a href="" class="reset">Reset</a>
    <a href="#" class="play">Play</a>
  </div>
</body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="{% static 'js/create_game.js' %}"></script>
  <script src="{% static 'js/csrf_protection.js' %}" ></script>

</html>

battle/templates/battle/game_not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Game not found</title>
</head>
<body>
  <h2>Game not found</h2>
</body>
</html>

battle/templates/battle/game_user1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Player 1</title>
  <link rel="stylesheet" href="{% static 'css/game_user1.css' %}">
</head>
<body>
  <div class="usernames">
    <H2 class="first-player">{{ game.player1.user }}</H2>
    <H2 class="second-player">
      {% if game.player2 == None %}
        Waiting for the enemy
      {% else %}
        {{ game.player2.user }}
      {% endif %}

    </H2>
  </div>
  <div id="battlefield1">
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
  </div>
  <div id="battlefield2">
    <div class="cell2" type="button"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
  </div>
  <br>
  <a href="{% url 'battle:surrender' %}"><h2>Surrender</h2></a>
</body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="{% static 'js/csrf_protection.js' %}" type="module"></script>
  <script src="{% static 'js/game_user1.js' %}"></script>
</html>

battle/templates/battle/game_user2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Player 2</title>
  <link rel="stylesheet" href="{% static 'css/game_user2.css' %}">
</head>
<body>
  <div class="usernames">
    <H2 class="first-player">{{ game.player2.user }}</H2>
    <H2 class="second-player">{{ game.player1.user }}</H2>
  </div>
  <div id="battlefield2">
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
    <div class="cell2"></div>
  </div>

  <div id="battlefield1">
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>
    <div class="cell1"></div>

  </div>
  <a href="{% url 'battle:surrender' %}"><h2>Surrender</h2></a>
</body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

  <script src="{% static 'js/game_user2.js' %}"></script>
</html>

battle/templates/battle/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Games</title>
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
{#  <script src="{% static 'js/jquery-3.6.0.js'%}"></script>#}

</head>
<body>
  <header>
    <div class="profile">

    </div>
    <a href="{% url 'users:logout_user' %}"><button class="logout-button">Log out</button></a>



  </header>
  <div class="best-games">

    <div class="list-best-games">
      <h2>Hello, {{ gamer.user.username }}</h2>
    </div>

  </div>
  <div class="container">
    <div class="games">
      {% for game in games %}
        <div class="game">
          <div class="username">
            {{ game.player1.user }}
          </div>
          {% if  game.player1.user != request.user %}
            <div class="join">
                <a href="{% url 'battle:join_game' game.room_name %}">Join</a>
            </div>
          {% endif %}
        </div>
      {% endfor %}
      {% if user_games < 1 %}
        <a href="{% url 'battle:create_game' %}">
        <div class="create-game">
          <h3>Create game</h3>
        </div>
        </a>
        <a href="">
          <div class="refresh-games">
            <h3>Refresh</h3>
          </div>
        </a>
      {% endif %}
    </div>
  </div>
</body>
  <script src="{% static 'js/index.js' %}"></script>
</html>

battle/templates/battle/lose_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="{% static 'css/lose.css' %}">
  <title>Lose</title>
</head>
<body>
  <div class="Main">
    <h1>You lose</h1>
    <h2><a  class="main-page" href="{% url 'battle:index' %}">Back to home page</a> -
      <a class="logout" href="{% url 'users:logout_user' %}">Log out</a></h2>
  </div>
</body>
</html>

battle/templates/battle/win_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="{% static 'css/win.css' %}">
  <title>Win</title>
</head>
<body>
  <div class="Main">
    <h1>You win</h1>
    <h2><a  class="main-page" href="{% url 'battle:index' %}">Back to home page</a> -
      <a class="logout" href="{% url 'users:logout_user' %}">Log out</a></h2>
  </div>
</body>
</html>